
C:\tileset_workshop>python compose_new.py !dda_test  1>testcase.log
Traceback (most recent call last):
  File "compose_new.py", line 321, in <module>
    tmp_merged_pngs = ts_data.walk_dirs(refs)
  File "compose_new.py", line 279, in walk_dirs
    merged = self.merge_row(refs)
  File "compose_new.py", line 234, in merge_row
    vips_image = Vips.Image.pngload(png_pathname)
  File "C:\Users\******\AppData\Local\Programs\Python\Python38\lib\site-packages
\pyvips\vimage.py", line 135, in call_function
    return pyvips.Operation.call(name, *args, **kwargs)
  File "C:\Users\******\AppData\Local\Programs\Python\Python38\lib\site-packages
\pyvips\voperation.py", line 282, in call
    raise Error('unable to call {0}'.format(operation_name))
pyvips.error.Error: unable to call pngload
  !dda_test/pngs_normal_32x32\furniture\terrains\f_pillow_fort/f_pillow_fort_t_c
onnection_3.png: unable to open for read
windows error: The program issued a command but the command length is incorrect.



